version: '2'
services:
  backend-nginx:
    build:
      context: .
      dockerfile: docker-concrescent3/build/Dockerfile.Backend.Nginx
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./docker-concrescent3/backend.php:/app/config.php:ro
    networks:
      - ccrscnt
  backend-php-fpm:
    build:
      context: .
      dockerfile: docker-concrescent3/build/Dockerfile.Backend.PHP-FPM
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./msmtprc:/etc/msmtprc:ro
      - ./docker-concrescent3/backend.php:/app/config.php:ro
      - ./logs/php-fpm:/app/logs
    networks:
      - ccrscnt
  frontend:
    build:
      context: .
      dockerfile: docker-concrescent3/build/Dockerfile.Frontend
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - ccrscnt
  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_PASSWORD=concrescent
      - MYSQL_USER=concrescent
      - MYSQL_DATABASE=concrescent
      - TZ=America/New_York
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpasswd --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - ccrscnt

networks:
  ccrscnt:
