version: '3.8'
services:
  concrescent:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./msmtprc:/etc/msmtprc:ro
      - ./concrescent.php:/var/www/html/config/config.php:ro
  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_PASSWORD=concrescent
      - MYSQL_USER=concrescent
      - MYSQL_DATABASE=concrescent
      - TZ=Europe/Paris
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpasswd --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
