version: '2'
services:
  concrescent:
    build:
      context: .
      dockerfile: docker-concrescent2/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./msmtprc:/etc/msmtprc:ro
      - ./docker-concrescent2/concrescent.php:/var/www/html/config/config.php:ro
    networks:
      - ccrscnt
  mysql:
    image: mysql:8
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_PASSWORD=concrescent
      - MYSQL_USER=concrescent
      - MYSQL_DATABASE=concrescent
      - TZ=America/Los_Angeles
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpasswd --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - ccrscnt

networks:
  ccrscnt:
